name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - uses: mr-smithers-excellent/docker-build-push@v4
      id: docker_build
      name: Build and push
      with:
        image: chekkan/rabbitmq
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag: 3.7.10
